### ISSUE TITLE
PERCABANGAN : JIKA

### ISSUE THREAD

**Issue by anak10thn** [baik-lang/baik-next#1]
vote baiknya menggunakan kata "jika tidak" atau "atau" untuk medeklarasikan kondisi "if else"
### A) Jika Tidak
```
jika (a > 1){
# expression
}
jikatidak (a > 0){
# expression
}
lainnya{
# expression
}
```
### B) Atau
```
jika (a > 1){
# expression
}
atau (a > 0){
# expression
}
lainnya{
# expression
}
```

**Comment by muslih** [comment]
saya vote A

**Comment by juniorralali** [comment]
vote B

**Comment by anak10thn** [comment]
terima kasih guys untuk masukannya, mumpung yg ngevote baru dua issue ini masih gw open

**Comment by handrawan112** [comment]
Vote b

**Comment by muhammadhanif** [comment]
saya pilih **B**

**Comment by fiqi1992** [comment]
Vote B
alasan: simple is better.
