### ISSUE TITLE
BAIK Paket Manajer

### ISSUE THREAD

**Issue by anak10thn** [baik-lang/baik-next#2]
baik akan memiliki alat pengelolaan paket, yang sementara di namakan BPM (baik paket manajer)
$bpm install libsqlite
$bpm install https://github.com/baik-lang/libsqlite
beberapa usulan nama sudah bisa buat kalian pilih nama yang cocok untuk paket manajer baik

a. buntel https://kbbi.web.id/buntel
b. bakul https://kbbi.web.id/bakul
c. lumbung https://kbbi.web.id/lumbung
d. kemas https://kbbi.web.id/kemas
e. bago (nama lain karung goni)
f. TKP (Tata Kelola Pustaka)

**Comment by handrawanw** [comment]
BPM ( Baik Paket Manajer )

**Comment by handrawanw** [comment]
*Bakul paket
Lebih ke indonesia bang.

**Comment by muhammadhanif** [comment]
c. Lumbung

**Comment by ayatmaulana** [comment]
Bakul 👆

**Comment by AgungPrabowo** [comment]
bakul

**Comment by juniorralali** [comment]
Bakul

**Comment by fiqi1992** [comment]
Lumbung

**Comment by jebeng83** [comment]
Bakul

**Comment by anak10thn** [comment]
ok di putuskan namanya bakul yah
